name: Scheduled Repo Sync
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync with Upstream
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync Upstream
        uses: fabasoad/data-sync-action@v1.0.2
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repo: F100Pilot/stremio-addon-streamimdb
          upstream_branch: main
          target_branch: main
